# aws cloudformation deploy --template-file cloudfront_s3.yaml --capabilities CAPABILITY_IAM --stack-name cloudfront-s3  --parameter-overrides DomainName=cloudfront-s3-demo HostedZoneName=dev.sudocode.sg --tags AppManagerCFNStackKey=cloudfront-s3
# aws cloudformation delete-stack --stack-name cloudfront-s3
Parameters:
  HostedZoneName:
    Type: String
    Default: ""

  DomainName:
    Type: String
    Default: ""

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketNamePrefix: demo-cloudfront
      BucketNamespace: account-regional

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DemoBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${DemoBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}

  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "${DomainName}.${HostedZoneName}"
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}.${HostedZoneName}"
      ValidationMethod: "DNS"
      DomainValidationOptions:
        - DomainName: !Sub "${DomainName}.${HostedZoneName}"
          HostedZoneId: !ImportValue "dns:HostedZoneId"
        - DomainName: !Sub "www.${DomainName}.${HostedZoneName}"
          HostedZoneId: !ImportValue "dns:HostedZoneId"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: s3-oac
        Description: OAC for private S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: true
        Comment: CloudFront distribution for private S3 bucket
        Aliases:
          - !Sub "${DomainName}.${HostedZoneName}"
          - !Sub "www.${DomainName}.${HostedZoneName}"

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt DemoBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true

          AllowedMethods:
            - GET
            - HEAD

          CachedMethods:
            - GET
            - HEAD

          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

        ViewerCertificate:
          AcmCertificateArn: !Ref SslCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  ApexDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue "dns:HostedZoneId"
      Name: !Sub "${DomainName}.${HostedZoneName}"
      Type: A
      AliasTarget:
        # The Hosted Zone ID for CloudFront is a fixed global constant (Z2FDTNDATAQYW2)
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        EvaluateTargetHealth: false

  WwwDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue "dns:HostedZoneId"
      Name: !Sub "www.${DomainName}.${HostedZoneName}"
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  CloudfrontDistributionUrl:
    Description: 'The URL of the cloudfront distribution'
    Value: !GetAtt CloudfrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}:CloudFrontUrl'

  DemoBucketUri:
    Description: "The full account-regional bucket name"
    Value: !Sub "s3://${DemoBucket}"
